### ISSUE TITLE
Update enrollment term for graduate offer letters

### ISSUE THREAD

**Issue by wjl-simon** [WildChickenUniversity/WildChickenUniversity#11]
The academic semester indicated in graduate offer letters is still Fall 2022 while now is already 2023, fix it please :）

**Comment by wjl-simon** [comment]
> * template updated 🐔
> * jsDelivr cache purged 🐔
> 
> done this message is written by a chicken from WCU. 🐔

Cool, updated in minutes LOL

**Comment by Mr-Sheep** [comment]
> Cool, updated in minutes LOL

Chicken speed

**Comment by wjl-simon** [comment]
> > Cool, updated in minutes LOL
> 
> Chicken speed

BWT some suggestions: You may consider making a box for the enrollment year in your letter template and fill in that blank using scripts as what you did for the name and the date fields.

In your assets/admission/script.js you can do something like like retrieving the `currentYear` and `currentMonth`. For `currentMonth` no latter than September (or October, of your choice) you simply insert `currentYear` (in some correct format), otherwise you put in `currentYear + 1`. This should save you a lot of work from manually updating the template every year without too many big jobs.
