### ISSUE TITLE
Font issue with generated diploma

### ISSUE THREAD

**Issue by Mr-Sheep** [WildChickenUniversity/WildChickenUniversity#9]
> @Mr-Sheep but I'm trying to print English text. this is the certificate I got open in Chrome browser: ![image](https://user-images.githubusercontent.com/97216571/148485317-a000ff4a-39ac-486e-8b4b-5e1c76f72570.png) this is how it looks like in Adobe: ![image](https://user-images.githubusercontent.com/97216571/148485407-d7d07e55-9dc6-4701-92b0-e75a4cd5f919.png)

Hey @Cwang73, I am working on a mascot project for WCU and I cannot replicate this issue. But I have generated one for you.

[WCU_Graduation_Certificate_Xiaoyu_Wang_Jan_07_2022.pdf](https://github.com/WildChickenUniversity/WildChickenUniversity/files/7826098/WCU_Graduation_Certificate_Xiaoyu_Wang_Jan_07_2022.pdf)

_Originally posted by @Mr-Sheep in https://github.com/WildChickenUniversity/WildChickenUniversity/issues/6#issuecomment-1007111095_

**Comment by Cwang73** [comment]
@Mr-Sheep hey, I always use a VPN to access both Github and WCU pages, not sure if it's the proxy's problem. I found your "download" thing somewhat interesting, I'll try using FDM to download the diploma instead of using the default web downloader when I get my own laptop. Would keep you updated!

**Comment by Cwang73** [comment]
@Mr-Sheep hi there, tried on my Mac and it worked perfectly
![WCU Diploma](https://user-images.githubusercontent.com/97216571/148626369-4b882cb0-365d-499a-8c25-14e8c93d1dbf.jpg)

**Comment by Mr-Sheep** [comment]
> It still presists ![image](https://user-images.githubusercontent.com/28757366/165245326-9cc3641b-28f6-4da7-ae7e-1d04edbef2fd.png)

seems like only Windows PC had difficulties with the pdf-lib.js library, you might wanna try with macOS.

**Comment by Cwang73** [comment]
> > It still presists ![image](https://user-images.githubusercontent.com/28757366/165245326-9cc3641b-28f6-4da7-ae7e-1d04edbef2fd.png)
> 
> seems like only Windows PC had difficulties with the pdf-lib.js library, you might wanna try with macOS.

yup I figured it out but really strange huh

**Comment by ZhiyuanChen** [comment]
> > It still presists ![image](https://user-images.githubusercontent.com/28757366/165245326-9cc3641b-28f6-4da7-ae7e-1d04edbef2fd.png)
> 
> seems like only Windows PC had difficulties with the pdf-lib.js library, you might wanna try with macOS.

Actually I'm using arch. Unfortunately mac is too wake to meet my needs

**Comment by Mr-Sheep** [comment]
macOS is indeed weaker than linux distros, but it seems to be the only os that works with pdf-lib’s embedded font ¯\_(ツ)_/¯

**Comment by Mr-Sheep** [comment]
> yup I figured it out but really strange huh

turns out pdf-lib.js does not have a good support for woff/woff2.
